### ISSUE TITLE
[Issue] Couldn't make it work, can't drag entities while holding Shift.

### ISSUE THREAD

**Issue by intemptesta** [xurxodiz/foundryvtt-entity-tiles#5]
Foundry VTT 0.7.7
D&D5e 1.1.1

I couldn't drag entities while holding Shift. If I drag them by the name it won't follow, if I drag them by the icon it will follow and deploy as normal but not as tile.
I suspect some modules to compete at using Shift key with this module, I'll try with a clean world when I have times.

**Comment by xurxodiz** [comment]
Hi! Thanks for your report. I freshly installed D&D5 1.1.1 and tested dragging an actor and a journal entry in a newly created world: they worked! There's probably some other module interfering, as you suspect. I'll try speeding up work on #2 so the key can be customized and the clash avoided.

In the meantime please do come back with more info if you have it.

**Comment by intemptesta** [comment]
Found the culprit!! It's [**Drag Upload Module Version 1.5.1**](https://foundryvtt.com/packages/dragupload/)
When I disable it, Entity Tiles work as intended. It works only if I hold the Shift key after dragging them out, though.

**Comment by xurxodiz** [comment]
Awesome! I'll try to check that module to find out where the possible clash lies.

It's weird about the Shift press, though. It works for me whether I press shift before clicking and dragging the entity or I press it while already dragging. What entity are you trying it out? Is it a fresh new world? No other modules enabled, right?

**Comment by intemptesta** [comment]
Thanks for getting back to me!

About Shift after dragging, I found out it's happened to me on Chrome only. (with or without extension)
On Chrome it's happen to actors, journals, etc.
But on Firefox Shift before dragging work fine for every entities, it's a fresh world.

**Comment by xurxodiz** [comment]
Lesson learned: I should've started asking about your browser!

It does happen to me too in Chrome though not in Firefox, I'll try to dig why's that.

**Comment by xurxodiz** [comment]
Hey! So I just uploaded a new version (0.1.1) that allows setting a custom key (alt, meta, shift or control) as the designated key. This should work around any package incompatibility.

I've also tested the module in Firefox (Win, Mac), Chrome (Win, Mac) and Edge (Win) and decided to change the default to Alt as that's the only key with no drawbacks in any platform or browser. I've compiled a list of known problems in the README.

I think this closes this issue. If you are still unhappy or finding trouble, do let me know and we'll reopen it!

**Comment by intemptesta** [comment]
Hi, thanks for new update.
I could only do a quick test on Firefox and key switching works flawlessly, great job!

Unfortunately look like incompatibility with Drag Upload didn't go away, I still need to disable it for Entity Tiles to work.
Maybe it's not about the key binding, my two-cent is about how they control the working area for dropping images into tokens...

But it's just a quick test, didn't test with Chrome yet, and I'll be away from PC for multiple days. After that I will try to do more test and get back to you again.

**Comment by xurxodiz** [comment]
Hmm, ok, I checked the code and saw what the issue is. You are right: both modules are trying to exclusively handle dropping into the canvas (silly me forgot I actually copied the hook code from them 😅).

If there's a way to solve this incompatibility, I currently don't know it. Only solution I can think of is to eventually merge both plugins :/

**Comment by intemptesta** [comment]
Understood, and it's ok. At least I'm able to notify you of this issue.

I think I can work around it, enabling one of these modules at a time. Drag Upload while setting up, and Entity Tiles while gaming.

Entity Tiles helps me a lot with vehicles, map assets, etc. It's a nice tool to have!

**Comment by xurxodiz** [comment]
I'm so glad you find it useful! :) Good to know there's a workaround that doesn't impact you too much.

I'm gonna make a new ticket referring specifically to the incompatibility with DragUpload so the conversation can follow there if new findings arise.
